import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const destFile = path.join(__dirname, '../src/data/destinations.json');
const data = JSON.parse(fs.readFileSync(destFile, 'utf8'));
const existingIds   = new Set(data.map(d => d.id));
const existingNames = new Set(data.map(d => d.name));

const NEW_DESTINATIONS = [
  // ── 離島 ──
  {
    id: 'mikurajima', name: '御蔵島', type: 'destination',
    region: '伊豆諸島', prefecture: '東京都',
    departures: ['東京'],
    isIsland: true, destType: 'island',
    hub: 'tokyo-o',
    stayAllowed: ['1night', '2night'],
    lat: 33.8822, lng: 139.5983,
    tags: ['島', '自然', 'イルカ', '秘境'],
    weight: 1.5,
    description: 'イルカとの共泳で知られる秘境の島。野生のイルカが至近距離で泳ぐ神秘的な体験ができる。',
    catch: '海に入ると、野生のイルカが隣にいた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'hiburi', name: '日振島', type: 'destination',
    region: '四国', prefecture: '愛媛県',
    departures: ['宇和島'],
    isIsland: true, destType: 'island',
    hub: 'hiroshima-t',
    stayAllowed: ['1night', '2night'],
    lat: 32.7278, lng: 132.2339,
    tags: ['島', '自然', '海', '秘境'],
    weight: 1.4,
    description: '愛媛県最西端に浮かぶ静かな離島。温暖な気候と透明な宇和海が魅力の漁師島。',
    catch: '南国の光の中に、古い漁村が残っていた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'toshima-uwajima', name: '戸島', type: 'destination',
    region: '四国', prefecture: '愛媛県',
    departures: ['宇和島'],
    isIsland: true, destType: 'island',
    hub: 'hiroshima-t',
    stayAllowed: ['1night', '2night'],
    lat: 32.8022, lng: 132.4408,
    tags: ['島', '自然', '海'],
    weight: 1.3,
    description: '宇和海に浮かぶ静かな離島。真珠養殖が盛んな穏やかな漁村の風景が広がる。',
    catch: '真珠が育つ静かな海で、時間の流れが変わった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'tonaki', name: '渡名喜島', type: 'destination',
    region: '沖縄', prefecture: '沖縄県',
    departures: ['那覇'],
    isIsland: true, destType: 'island',
    hub: 'naha',
    stayAllowed: ['1night', '2night'],
    lat: 26.3685, lng: 127.1534,
    tags: ['島', '自然', '秘境', '海'],
    weight: 1.4,
    description: '人口約300人、赤瓦の集落が残る沖縄の秘境離島。昔ながらの琉球の暮らしが息づく。',
    catch: '赤瓦の集落で、沖縄の時間に浸った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'yorojima', name: '与路島', type: 'destination',
    region: '九州', prefecture: '鹿児島県',
    departures: ['奄美大島'],
    isIsland: true, destType: 'island',
    hub: 'kagoshima',
    stayAllowed: ['1night', '2night'],
    lat: 28.2700, lng: 129.3600,
    tags: ['島', '自然', '秘境', '海'],
    weight: 1.4,
    description: '奄美大島近くに浮かぶ人口僅かの超秘境島。手つかずの珊瑚礁と原生林が残る。',
    catch: '人より自然の方が多い島で、静寂に包まれた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'kuchinoerabu', name: '口永良部島', type: 'destination',
    region: '九州', prefecture: '鹿児島県',
    departures: ['屋久島'],
    isIsland: true, destType: 'island',
    hub: 'kagoshima',
    stayAllowed: ['1night', '2night'],
    lat: 30.4430, lng: 130.2179,
    tags: ['島', '火山', '自然', '秘境'],
    weight: 1.5,
    description: '活火山を持つ屋久島の隣島。温泉と火山地形が作り出す異世界感が漂う秘境の島。',
    catch: '火山が今も生きている島で、湯煙に包まれた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'nishinoshima', name: '西ノ島', type: 'destination',
    region: '中国', prefecture: '島根県',
    departures: ['境港', '松江'],
    isIsland: true, destType: 'island',
    hub: 'osaka-t',
    stayAllowed: ['1night', '2night'],
    lat: 36.0631, lng: 132.9935,
    tags: ['島', '自然', '絶景', '秘境'],
    weight: 1.5,
    description: '隠岐諸島の火山島。国賀海岸の荒々しい断崖と放牧の馬が共存する絶景の島。',
    catch: '断崖に馬が立っていた。それだけで絵になった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'minamidaitojima', name: '南大東島', type: 'destination',
    region: '沖縄', prefecture: '沖縄県',
    departures: ['那覇'],
    isIsland: true, destType: 'island',
    hub: 'naha',
    stayAllowed: ['1night', '2night'],
    lat: 25.8281, lng: 131.2330,
    tags: ['島', '秘境', '自然', '文化'],
    weight: 1.5,
    description: 'サトウキビと断崖に囲まれた絶海の孤島。那覇から飛行機1時間の先にある独特の文化と地形。',
    catch: '那覇からも遠い島で、特別な孤独感と出会った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'kitadaitojima', name: '北大東島', type: 'destination',
    region: '沖縄', prefecture: '沖縄県',
    departures: ['那覇'],
    isIsland: true, destType: 'island',
    hub: 'naha',
    stayAllowed: ['1night', '2night'],
    lat: 25.9456, lng: 131.3025,
    tags: ['島', '秘境', '自然'],
    weight: 1.4,
    description: '南大東島のさらに北に位置する絶海の離島。珊瑚礁の地形と星空が美しい最果ての島。',
    catch: '日本にこんな場所があるのかと思った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'sakushima', name: '佐久島', type: 'destination',
    region: '中部', prefecture: '愛知県',
    departures: ['名古屋'],
    isIsland: true, destType: 'island',
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.8433, lng: 136.9717,
    tags: ['島', 'アート', '自然', '海'],
    weight: 1.4,
    description: '愛知県三河湾に浮かぶ小さな離島。アート作品と昔ながらの漁師町が共存する島。',
    catch: 'アートと漁村が混ざった島で、意外な感動があった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'shinojima', name: '篠島', type: 'destination',
    region: '中部', prefecture: '愛知県',
    departures: ['名古屋'],
    isIsland: true, destType: 'island',
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.7858, lng: 136.9993,
    tags: ['島', '海', 'グルメ', '自然'],
    weight: 1.3,
    description: '伊勢神宮に毎年タイを奉納する歴史ある愛知の漁師島。新鮮な海鮮と島の静けさを味わえる。',
    catch: '伊勢に鯛を贈る島の、静かな漁港に立った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'himakajima', name: '日間賀島', type: 'destination',
    region: '中部', prefecture: '愛知県',
    departures: ['名古屋'],
    isIsland: true, destType: 'island',
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.8157, lng: 136.9560,
    tags: ['島', '海', 'グルメ', 'タコ'],
    weight: 1.3,
    description: 'タコとフグで有名な愛知県三河湾の離島。日帰りでも行ける手軽さと海の幸が魅力。',
    catch: '蛸の足より多い笑顔の島で、海の幸に溺れた。',
    requiresCar: false, hotelLinks: null,
  },
  // ── マイナー・穴場系 ──
  {
    id: 'ukujima', name: '鵜来島', type: 'destination',
    region: '四国', prefecture: '高知県',
    departures: ['高知'],
    isIsland: true, destType: 'island',
    hub: 'hiroshima-t',
    stayAllowed: ['1night', '2night'],
    lat: 32.7800, lng: 132.5650,
    tags: ['島', '海', 'ダイビング', '秘境'],
    weight: 1.5,
    description: '高知県最果てに浮かぶダイビングの聖地。魚影が濃く透明度抜群の海中世界が広がる。',
    catch: '水中に入ると、別の宇宙があった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'hotokegaura', name: '仏ヶ浦', type: 'destination',
    region: '東北', prefecture: '青森県',
    departures: ['青森', '八戸'],
    isIsland: false,
    hub: 'sendai-t',
    stayAllowed: ['1night', '2night'],
    lat: 41.3000, lng: 141.0500,
    tags: ['絶景', '奇岩', '自然', '秘境'],
    weight: 1.5,
    description: '下北半島の奇岩群が連なる秘境の絶景地。白い凝灰岩が海に切り立つ自然の造形美は圧巻。',
    catch: '白い岩が海から生えていた。人間が作れない景色だった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'shiibamura', name: '椎葉村', type: 'destination',
    region: '九州', prefecture: '宮崎県',
    departures: ['宮崎', '福岡'],
    isIsland: false,
    hub: 'fukuoka-t',
    stayAllowed: ['1night', '2night'],
    lat: 32.4833, lng: 131.0833,
    tags: ['秘境', '山', '文化', '自然'],
    weight: 1.5,
    description: '平家落人伝説が残る宮崎の秘境山村。日本三大秘境の一つで、山深い集落に時代が止まっている。',
    catch: '山の奥に、時代が止まった村があった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'sugari', name: '須賀利', type: 'destination',
    region: '近畿', prefecture: '三重県',
    departures: ['名古屋', '大阪'],
    isIsland: false,
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.1700, lng: 136.4800,
    tags: ['漁村', '秘境', '海', '自然'],
    weight: 1.4,
    description: '山と海に囲まれた三重県の小さな漁村。陸から孤立した地形が生む静けさが旅人を引き寄せる。',
    catch: '山と海に挟まれた漁村で、世界から切り離された感覚になった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'kuki', name: '九鬼', type: 'destination',
    region: '近畿', prefecture: '三重県',
    departures: ['名古屋', '大阪'],
    isIsland: false,
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.1850, lng: 136.4900,
    tags: ['漁村', '秘境', '海', '自然'],
    weight: 1.4,
    description: '三重県尾鷲市の入り江に静かに佇む漁村。山と海に囲まれた秘境感あふれる集落。',
    catch: '細い路地の先に海があった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'tateyamasaki', name: '楯ヶ崎', type: 'destination',
    region: '近畿', prefecture: '三重県',
    departures: ['名古屋', '大阪'],
    isIsland: false,
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 33.9667, lng: 136.5500,
    tags: ['絶景', '断崖', '自然', '秘境'],
    weight: 1.5,
    description: '三重県熊野灘に突き出た柱状節理の断崖。南紀最大の奇勝とも呼ばれる大岩壁が海に迫る。',
    catch: '柱のような岩が海に立ち並ぶ光景に言葉を失った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'furukawa-mie', name: '古江', type: 'destination',
    region: '近畿', prefecture: '三重県',
    departures: ['名古屋', '大阪'],
    isIsland: false,
    hub: 'nagoya-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.1500, lng: 136.4600,
    tags: ['漁村', '秘境', '海', '自然'],
    weight: 1.3,
    description: '紀伊半島南部の静かな漁村。外洋に面した穏やかな集落で、海の音だけが聞こえる。',
    catch: '何もない漁村に泊まると、静けさの意味がわかった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'okinoshima-kochi', name: '沖ノ島', type: 'destination',
    region: '四国', prefecture: '高知県',
    departures: ['高知'],
    isIsland: true, destType: 'island',
    hub: 'hiroshima-t',
    stayAllowed: ['1night', '2night'],
    lat: 32.7614, lng: 132.5469,
    tags: ['島', '海', '秘境', 'ダイビング'],
    weight: 1.5,
    description: '高知県柏島沖の岩礁島。手つかずの珊瑚礁と圧倒的な透明度を誇るダイビングスポット。',
    catch: '水中の密度が違った。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'nushima', name: '沼島', type: 'destination',
    region: '近畿', prefecture: '兵庫県',
    departures: ['大阪', '神戸'],
    isIsland: true, destType: 'island',
    hub: 'osaka-t',
    stayAllowed: ['1night', '2night'],
    lat: 34.0000, lng: 134.8417,
    tags: ['島', '神話', '自然', '海'],
    weight: 1.4,
    description: '国生み神話の舞台ともいわれる淡路島南の離島。神秘的な巨石と静かな漁村が旅人を迎える。',
    catch: '神話が生まれた島で、なぜか静かな気持ちになった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'kasadojima', name: '笠戸島', type: 'destination',
    region: '中国', prefecture: '山口県',
    departures: ['広島', '山口'],
    isIsland: true, destType: 'island',
    hub: 'hiroshima-t',
    stayAllowed: ['1night', '2night'],
    lat: 33.9358, lng: 131.8217,
    tags: ['島', '自然', '海', 'ドライブ'],
    weight: 1.3,
    description: 'ひらめ養殖発祥の地として知られる山口県の離島。橋で繋がるアクセス容易な自然豊かな島。',
    catch: 'ひらめの聖地で、穏やかな瀬戸内の海に包まれた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'noko-island', name: '能古島', type: 'destination',
    region: '九州', prefecture: '福岡県',
    departures: ['福岡'],
    isIsland: true, destType: 'island',
    hub: 'fukuoka-t',
    stayAllowed: ['1night', '2night'],
    lat: 33.6400, lng: 130.3400,
    tags: ['島', '自然', '花', '海'],
    weight: 1.3,
    description: '博多港からフェリー10分のアイランドパーク。花畑と博多湾の穏やかな景色が広がる癒しの島。',
    catch: '博多の沖に、のどかな花の島があった。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'akiyamago', name: '秋山郷', type: 'destination',
    region: '中部', prefecture: '新潟県',
    departures: ['新潟', '長野'],
    isIsland: false,
    hub: 'tokyo-o',
    stayAllowed: ['1night', '2night'],
    lat: 36.9833, lng: 138.5833,
    tags: ['秘境', '山', '自然', '温泉'],
    weight: 1.5,
    description: '長野・新潟県境の秘境山村。合掌造りの宿と渓谷美、秘湯が三拍子揃った山奥の別世界。',
    catch: '辺境の温泉宿で、山の夜を独占した。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'okitama', name: '置賜', type: 'destination',
    region: '東北', prefecture: '山形県',
    departures: ['山形'],
    isIsland: false,
    hub: 'sendai-t',
    stayAllowed: ['1night', '2night'],
    lat: 38.0922, lng: 140.0976,
    tags: ['山', '自然', '温泉', '歴史'],
    weight: 1.3,
    description: '上杉家ゆかりの歴史が残る山形南部の盆地。米沢の武将文化と温泉、農村風景が混在する地域。',
    catch: '米沢の武士文化と温泉が、今も生きていた。',
    requiresCar: false, hotelLinks: null,
  },
  {
    id: 'osorezan-area', name: '恐山エリア', type: 'destination',
    region: '東北', prefecture: '青森県',
    departures: ['青森', '八戸'],
    isIsland: false,
    hub: 'sendai-t',
    stayAllowed: ['1night', '2night'],
    lat: 41.3833, lng: 141.0583,
    tags: ['秘境', '霊場', '温泉', '自然'],
    weight: 1.5,
    description: '日本三大霊場の一つ、下北半島のカルデラ湖畔に広がる恐山。荒涼とした硫黄地形と温泉が独特の世界観を作る。',
    catch: '賽の河原に立つと、生と死の境界が消えた。',
    requiresCar: false, hotelLinks: null,
  },
];

let added = 0;
let skipped = 0;
const toAdd = [];

NEW_DESTINATIONS.forEach(d => {
  if (existingIds.has(d.id)) {
    console.log(`⏭ スキップ（ID重複）: ${d.name} [${d.id}]`);
    skipped++;
    return;
  }
  if (existingNames.has(d.name)) {
    console.log(`⏭ スキップ（名前重複）: ${d.name}`);
    skipped++;
    return;
  }
  toAdd.push(d);
  added++;
});

data.push(...toAdd);
fs.writeFileSync(destFile, JSON.stringify(data, null, 2), 'utf8');

console.log(`\n✅ 新規追加: ${added}件 / スキップ: ${skipped}件 / 総件数: ${data.length}件`);
toAdd.forEach(d => console.log(`   追加: ${d.name} [${d.id}]`));
